version: "3.8"
services:
  database:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warehouse_db
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: warehouse_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/warehouse_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - database
